
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
  0%|                                                                                                                       | 0/3 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/Users/siddharthsuresh/Projects/Wisconsin/ConceptualAlignmentLanguage/scripts/main.py", line 61, in <module>
    main()
  File "/Users/siddharthsuresh/Projects/Wisconsin/ConceptualAlignmentLanguage/scripts/main.py", line 54, in main
    training.train(args.model_save_dir, args.num_models, args.epochs, args.num_classes, args.batch_size,
  File "/Users/siddharthsuresh/Projects/Wisconsin/ConceptualAlignmentLanguage/src/training.py", line 59, in train
    val_accuracy= model.training_loop(train_data = train_data,
  File "/Users/siddharthsuresh/Projects/Wisconsin/ConceptualAlignmentLanguage/src/models/ConvAutoencoder.py", line 225, in training_loop
    for epoch in tqdm(range(epochs)):
TypeError: 'module' object is not callable